# Generated by Django 5.2.5 on 2025-08-31 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataMigrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "migration_type",
                    models.CharField(
                        choices=[
                            ("danmaku", "弹幕数据"),
                            ("gift", "礼物数据"),
                            ("room", "房间数据"),
                            ("all", "全部数据"),
                        ],
                        max_length=20,
                        verbose_name="迁移类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("total_records", models.IntegerField(default=0, verbose_name="总记录数")),
                (
                    "success_records",
                    models.IntegerField(default=0, verbose_name="成功记录数"),
                ),
                (
                    "failed_records",
                    models.IntegerField(default=0, verbose_name="失败记录数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "数据迁移日志",
                "verbose_name_plural": "数据迁移日志",
                "db_table": "data_migration_logs",
                "indexes": [
                    models.Index(
                        fields=["migration_type"], name="data_migrat_migrati_408f13_idx"
                    ),
                    models.Index(
                        fields=["status"], name="data_migrat_status_72fa80_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="data_migrat_start_t_5097b8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="data_migrat_created_22a2a6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LiveRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="房间ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="未知标题", max_length=255, verbose_name="直播间标题"
                    ),
                ),
                (
                    "uname",
                    models.CharField(
                        default="未知主播", max_length=100, verbose_name="主播用户名"
                    ),
                ),
                ("face", models.URLField(blank=True, null=True, verbose_name="主播头像")),
                ("online", models.IntegerField(default=0, verbose_name="在线人数")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未开播"), (1, "直播中"), (2, "轮播")],
                        default=0,
                        verbose_name="直播状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "直播间",
                "verbose_name_plural": "直播间",
                "db_table": "live_rooms",
                "indexes": [
                    models.Index(
                        fields=["room_id"], name="live_rooms_room_id_e44e51_idx"
                    ),
                    models.Index(
                        fields=["status"], name="live_rooms_status_a3186e_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="live_rooms_updated_510c1d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitoringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, unique=True, verbose_name="任务名称"),
                ),
                ("room_ids", models.TextField(default="[]", verbose_name="监控房间ID列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "已停止"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("error", "错误"),
                        ],
                        default="stopped",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "collected_danmaku",
                    models.IntegerField(default=0, verbose_name="收集弹幕数"),
                ),
                (
                    "collected_gifts",
                    models.IntegerField(default=0, verbose_name="收集礼物数"),
                ),
                ("error_count", models.IntegerField(default=0, verbose_name="错误次数")),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="最近错误"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "监控任务",
                "verbose_name_plural": "监控任务",
                "db_table": "monitoring_tasks",
                "indexes": [
                    models.Index(
                        fields=["status"], name="monitoring__status_dc082d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="monitoring__created_871a99_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="monitoring__updated_99836e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GiftData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.BigIntegerField(db_index=True, verbose_name="用户UID")),
                (
                    "username",
                    models.CharField(
                        default="匿名用户", max_length=100, verbose_name="用户名"
                    ),
                ),
                ("gift_name", models.CharField(max_length=100, verbose_name="礼物名称")),
                ("gift_id", models.IntegerField(db_index=True, verbose_name="礼物ID")),
                ("num", models.IntegerField(default=1, verbose_name="礼物数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="礼物单价"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=18, verbose_name="总价值"
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="发送时间")),
                (
                    "medal_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="粉丝牌名称"
                    ),
                ),
                ("medal_level", models.IntegerField(default=0, verbose_name="粉丝牌等级")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_set",
                        to="live_data.liveroom",
                        verbose_name="房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "礼物数据",
                "verbose_name_plural": "礼物数据",
                "db_table": "gift_data",
                "indexes": [
                    models.Index(
                        fields=["room", "timestamp"],
                        name="gift_data_room_id_922ba2_idx",
                    ),
                    models.Index(fields=["uid"], name="gift_data_uid_0bddf3_idx"),
                    models.Index(
                        fields=["username"], name="gift_data_usernam_5fe946_idx"
                    ),
                    models.Index(
                        fields=["gift_id"], name="gift_data_gift_id_b4d563_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="gift_data_timesta_df4cf7_idx"
                    ),
                    models.Index(
                        fields=["total_price"], name="gift_data_total_p_3c0e7a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="gift_data_created_b048fd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "uid", "gift_id", "timestamp"),
                        name="unique_gift",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DanmakuData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.BigIntegerField(db_index=True, verbose_name="用户UID")),
                (
                    "username",
                    models.CharField(
                        default="匿名用户", max_length=100, verbose_name="用户名"
                    ),
                ),
                ("message", models.TextField(verbose_name="弹幕内容")),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="发送时间")),
                (
                    "medal_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="粉丝牌名称"
                    ),
                ),
                ("medal_level", models.IntegerField(default=0, verbose_name="粉丝牌等级")),
                ("user_level", models.IntegerField(default=0, verbose_name="用户等级")),
                ("is_admin", models.BooleanField(default=False, verbose_name="是否管理员")),
                ("is_vip", models.BooleanField(default=False, verbose_name="是否VIP")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danmaku_set",
                        to="live_data.liveroom",
                        verbose_name="房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "弹幕数据",
                "verbose_name_plural": "弹幕数据",
                "db_table": "danmaku_data",
                "indexes": [
                    models.Index(
                        fields=["room", "timestamp"],
                        name="danmaku_dat_room_id_4b0e07_idx",
                    ),
                    models.Index(fields=["uid"], name="danmaku_dat_uid_d1e6a5_idx"),
                    models.Index(
                        fields=["username"], name="danmaku_dat_usernam_f6eb5e_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="danmaku_dat_timesta_542cce_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="danmaku_dat_created_694cfa_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "uid", "message", "timestamp"),
                        name="unique_danmaku",
                    )
                ],
            },
        ),
    ]
