# Generated by Django 5.2.5 on 2025-08-30 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.BigIntegerField(unique=True, verbose_name="房间ID")),
                (
                    "real_room_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="真实房间ID"
                    ),
                ),
                ("uname", models.CharField(max_length=100, verbose_name="主播名称")),
                ("title", models.CharField(max_length=200, verbose_name="直播间标题")),
                (
                    "area_name",
                    models.CharField(blank=True, max_length=50, verbose_name="分区名称"),
                ),
                (
                    "parent_area_name",
                    models.CharField(blank=True, max_length=50, verbose_name="父分区名称"),
                ),
                (
                    "uid",
                    models.BigIntegerField(blank=True, null=True, verbose_name="主播UID"),
                ),
                ("cover", models.URLField(blank=True, verbose_name="封面图片")),
                ("keyframe", models.URLField(blank=True, verbose_name="关键帧")),
                ("live_status", models.IntegerField(default=0, verbose_name="直播状态")),
                (
                    "is_monitoring",
                    models.BooleanField(default=False, verbose_name="是否监控中"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "直播间",
                "verbose_name_plural": "直播间",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="导出时间"
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("data_count", models.IntegerField(default=0, verbose_name="数据条数")),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="数据开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="数据结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("pending", "处理中"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live_data.room",
                        verbose_name="直播间",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据导出",
                "verbose_name_plural": "数据导出",
                "ordering": ["-export_time"],
            },
        ),
    ]
