# Generated by Django 5.2.5 on 2025-08-30 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.IntegerField(unique=True, verbose_name="房间ID")),
                ("uname", models.CharField(max_length=100, verbose_name="主播用户名")),
                ("title", models.CharField(max_length=200, verbose_name="直播间标题")),
                (
                    "area_name",
                    models.CharField(blank=True, max_length=50, verbose_name="分区名称"),
                ),
                (
                    "parent_area_name",
                    models.CharField(blank=True, max_length=50, verbose_name="父分区名称"),
                ),
                ("live_status", models.IntegerField(default=0, verbose_name="直播状态")),
                ("popularity", models.IntegerField(default=0, verbose_name="人气值")),
                (
                    "is_monitoring",
                    models.BooleanField(default=False, verbose_name="是否监控中"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "直播房间",
                "verbose_name_plural": "直播房间",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("gift_name", models.CharField(max_length=100, verbose_name="礼物名称")),
                ("gift_id", models.IntegerField(verbose_name="礼物ID")),
                ("num", models.IntegerField(default=1, verbose_name="礼物数量")),
                ("price", models.IntegerField(default=0, verbose_name="礼物价格")),
                (
                    "coin_type",
                    models.CharField(
                        default="silver", max_length=20, verbose_name="货币类型"
                    ),
                ),
                ("send_time", models.DateTimeField(verbose_name="发送时间")),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="接收时间"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live_data.liveroom",
                        verbose_name="所属房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "礼物数据",
                "verbose_name_plural": "礼物数据",
                "ordering": ["-send_time"],
            },
        ),
        migrations.CreateModel(
            name="DanmakuData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("uid", models.BigIntegerField(verbose_name="用户ID")),
                ("message", models.TextField(verbose_name="弹幕内容")),
                ("send_time", models.DateTimeField(verbose_name="发送时间")),
                ("send_time_timestamp", models.BigIntegerField(verbose_name="发送时间戳")),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="接收时间"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live_data.liveroom",
                        verbose_name="所属房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "弹幕数据",
                "verbose_name_plural": "弹幕数据",
                "ordering": ["-send_time"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="任务状态"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("danmaku_count", models.IntegerField(default=0, verbose_name="收集弹幕数")),
                ("gift_count", models.IntegerField(default=0, verbose_name="收集礼物数")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="live_data.liveroom",
                        verbose_name="监控房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控任务",
                "verbose_name_plural": "监控任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DataExport",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.AddIndex(
            model_name="giftdata",
            index=models.Index(
                fields=["room", "-send_time"], name="live_data_g_room_id_1264bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftdata",
            index=models.Index(
                fields=["username"], name="live_data_g_usernam_e34803_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftdata",
            index=models.Index(
                fields=["gift_name"], name="live_data_g_gift_na_13da25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="danmakudata",
            index=models.Index(
                fields=["room", "-send_time"], name="live_data_d_room_id_59ac0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="danmakudata",
            index=models.Index(
                fields=["username"], name="live_data_d_usernam_69fa6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="danmakudata",
            index=models.Index(
                fields=["send_time"], name="live_data_d_send_ti_d71f3d_idx"
            ),
        ),
    ]
